live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7f8c8d"
blue = "#3daee9"
cyan = "#16a085"
green = "#1cdc9a"
magenta = "#8e44ad"
red = "#c0392b"
white = "#ffffff"
yellow = "#fdbc4b"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#31363b"
blue = "#1b668f"
cyan = "#186c60"
green = "#17a262"
magenta = "#614a73"
red = "#783228"
white = "#63686d"
yellow = "#b65619"

[colors.footer_bar]
background = "#c5c8c6"
foreground = "#1d1f21"

[colors.normal]
black = "#232627"
blue = "#1d99f3"
cyan = "#1abc9c"
green = "#11d116"
magenta = "#9b59b6"
red = "#ed1515"
white = "#fcfcfc"
yellow = "#f67400"

[colors.primary]
background = "#000000"
bright_foreground = "#ffffff"
dim_foreground = "#eff0f1"
foreground = "#fcfcfc"

[colors.search.focused_match]
background = "#000000"
foreground = "#ffffff"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Space"
mode = "Vi|~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Escape"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "I"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "I"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "C"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Y"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "E"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Y"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Copy"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "V"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleLineSelection"
key = "V"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleBlockSelection"
key = "V"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleSemanticSelection"
key = "V"
mode = "Vi|~Search"
mods = "Alt"

[[keyboard.bindings]]
action = "Open"
key = "Return"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "CenterAroundViCursor"
key = "Z"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Up"
key = "K"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Down"
key = "J"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Left"
key = "H"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Right"
key = "L"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Up"
key = "Up"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Down"
key = "Down"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Left"
key = "Left"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Right"
key = "Right"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "First"
key = "Key0"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Last"
key = "Key4"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "Key6"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "High"
key = "H"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Middle"
key = "M"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Low"
key = "L"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SemanticLeft"
key = "B"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SemanticRight"
key = "W"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SemanticRightEnd"
key = "E"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "WordLeft"
key = "B"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRight"
key = "W"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRightEnd"
key = "E"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Bracket"
key = "Key5"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "Slash"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchBackward"
key = "Slash"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchNext"
key = "N"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchPrevious"
key = "N"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchConfirm"
key = "Return"
mode = "Search|Vi"

[[keyboard.bindings]]
action = "SearchCancel"
key = "Escape"
mode = "Search"

[[keyboard.bindings]]
action = "SearchCancel"
key = "C"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchClear"
key = "U"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchDeleteWord"
key = "W"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchHistoryPrevious"
key = "P"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchHistoryNext"
key = "N"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchHistoryPrevious"
key = "Up"
mode = "Search"

[[keyboard.bindings]]
action = "SearchHistoryNext"
key = "Down"
mode = "Search"

[[keyboard.bindings]]
action = "SearchFocusNext"
key = "Return"
mode = "Search|~Vi"

[[keyboard.bindings]]
action = "SearchFocusPrevious"
key = "Return"
mode = "Search|~Vi"
mods = "Shift"

[[keyboard.bindings]]
chars = "\f"
key = "K"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "HideOtherApplications"
key = "H"
mods = "Command|Alt"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Command"

[scrolling]
history = 30000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/opt/homebrew/bin/zsh"

[window]
decorations = "none"
option_as_alt = "OnlyLeft"
startup_mode = "Windowed"
