env:
  TERM: xterm-256color

font:
  normal:
    family: Monaco
    style: Regular
  bold:
    family: Monaco
    style: Bold
  italic:
    family: Monaco
    style: Italic
  size: 14.0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: true
draw_bold_text_with_bright_colors: true
live_config_reload: true
alt_send_esc: false
# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
#background_opacity: 0.7

mouse:
  url:
    launcher:
      program: open
    modifiers: None

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true

dynamic_title: true

# Colors (Tomorrow Night Bright)
colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '#eaeaea'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#d54e53'
    green:   '#b9ca4a'
    yellow:  '#e6c547'
    blue:    '#7aa6da'
    magenta: '#c397d8'
    cyan:    '#70c0ba'
    white:   '#424242'

  # Bright colors
  bright:
    black:   '#666666'
    red:     '#ff3334'
    green:   '#9ec400'
    yellow:  '#e7c547'
    blue:    '#7aa6da'
    magenta: '#b77ee0'
    cyan:    '#54ced6'
    white:   '#2a2a2a'

scrolling:
  history: 10000
  multiplier: 3

shell:
  program: /usr/local/bin/zsh
  args:
    - --login
key_bindings:
  - { key: Key0,   mods: Command,         action: ResetFontSize    }
  - { key: Equals, mods: Command,         action: IncreaseFontSize }
  - { key: Add,    mods: Command,         action: IncreaseFontSize }
  - { key: Minus,  mods: Command,         action: DecreaseFontSize }
  - { key: K,      mods: Command,         action: ClearHistory     }
  - { key: K,      mods: Command,         chars: "\x0c"            }
  - { key: V,      mods: Command,         action: Paste            }
  - { key: C,      mods: Command,         action: Copy             }
  - { key: H,      mods: Command,         action: Hide             }
  - { key: M,      mods: Command,         action: Minimize         }
  - { key: Q,      mods: Command,         action: Quit             }
  - { key: W,      mods: Command,         action: Quit             }
  - { key: Return,      mods: Command|Control, action: ToggleFullscreen }
  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,   mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageUp,   mods: Shift,   chars: "\x1b[5;2~",     mode: Alt        }
  - { key: PageUp,   mods: Control, chars: "\x1b[5;5~"                       }
  - { key: PageUp,   mods: Alt,     chars: "\x1b[5;3~"                       }
  - { key: PageUp,                  chars: "\x1b[5~"                         }
  - { key: PageDown, mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: PageDown, mods: Shift,   chars: "\x1b[6;2~",     mode: Alt        }
  - { key: PageDown, mods: Control, chars: "\x1b[6;5~"                       }
  - { key: PageDown, mods: Alt,     chars: "\x1b[6;3~"                       }
  - { key: PageDown,                chars: "\x1b[6~"                         }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }
