# Use tall and fullscreen layouts
layouts:
    - fullscreen
    - column

# Add "command" to the default mods
mod1:
    - option
    - shift
mod2:
    - option
    - shift
    - control

# Modify the amethyst relaunch to use x and not z
relaunch-amethyst:
    mod: mod2
    key: z

# Enable focus-follows-mouse
mouse-follows-focus: true
focus-follows-mouse: false

window-margins: false
window-margin-size: 0
