#!/usr/bin/env -S deno run --allow-read --allow-run --allow-env --allow-write

/**
 * PreCompact Hook (TS版)
 * transcript抽出 + git状態 → ai/state/<session_id>/assets.json
 * + ai/log/sessions/ に履歴保存
 *
 * AI/ネットワーク呼び出しなし（軽量）
 */

import { readAll } from "jsr:@std/io@0.224/read-all";
import {
  countTranscriptEntries,
  getFilesTouched,
  getGitBranch,
  getGitDirtyCount,
  getGitHeadSha,
  getLastAssistantText,
  getRecentUserMessages,
} from "./lib/session-context.ts";

interface PreCompactInput {
  trigger?: string;
  transcript_path?: string;
  session_id?: string;
  cwd?: string;
  custom_instructions?: string;
}

interface AssetsJson {
  schema_version: number;
  session_id: string;
  created_at: string;
  project_dir: string;
  trigger: string;
  custom_instructions: string | null;
  ttl_hours: number;
  git: {
    branch: string;
    head_sha: string;
    dirty_files: number;
  };
  recent_user_messages: string[];
  files_touched: string[];
  last_assistant_text: string;
  transcript_stats: {
    total_entries: number;
  };
}

async function atomicWrite(path: string, data: string): Promise<void> {
  const tmp = path + ".tmp." + crypto.randomUUID().slice(0, 8);
  await Deno.writeTextFile(tmp, data);
  await Deno.rename(tmp, path);
}

async function main(): Promise<void> {
  const raw = new TextDecoder().decode(await readAll(Deno.stdin));
  const input: PreCompactInput = JSON.parse(raw);

  const projectDir = Deno.env.get("CLAUDE_PROJECT_DIR");
  if (!projectDir) {
    Deno.exit(0);
  }

  const trigger = input.trigger ?? "unknown";
  const transcriptPath = input.transcript_path ?? "";
  const sessionId = input.session_id ?? "unknown";
  const cwd = input.cwd ?? projectDir;

  // Parallel extraction
  const [recentMsgs, filesTouched, lastAssistantText, branch, headSha, dirtyFiles, totalEntries] =
    await Promise.all([
      transcriptPath ? getRecentUserMessages(transcriptPath, 5, 200) : Promise.resolve([]),
      transcriptPath ? getFilesTouched(transcriptPath) : Promise.resolve([]),
      transcriptPath ? getLastAssistantText(transcriptPath) : Promise.resolve(""),
      getGitBranch(cwd),
      getGitHeadSha(cwd),
      getGitDirtyCount(cwd),
      transcriptPath ? countTranscriptEntries(transcriptPath) : Promise.resolve(0),
    ]);

  const assets: AssetsJson = {
    schema_version: 1,
    session_id: sessionId,
    created_at: new Date().toISOString(),
    project_dir: projectDir,
    trigger,
    custom_instructions: input.custom_instructions ?? null,
    ttl_hours: 24,
    git: {
      branch,
      head_sha: headSha,
      dirty_files: dirtyFiles,
    },
    recent_user_messages: recentMsgs,
    files_touched: filesTouched,
    last_assistant_text: lastAssistantText,
    transcript_stats: {
      total_entries: totalEntries,
    },
  };

  // Save assets.json
  const stateDir = `${projectDir}/ai/state/${sessionId}`;
  await Deno.mkdir(stateDir, { recursive: true });
  await atomicWrite(`${stateDir}/assets.json`, JSON.stringify(assets, null, 2));

  // Save session log (legacy format for backwards compat)
  const logDir = `${projectDir}/ai/log/sessions`;
  await Deno.mkdir(logDir, { recursive: true });

  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  const dateStr = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
  const timeStr = `${pad(now.getHours())}${pad(now.getMinutes())}`;
  const baseName = `${dateStr}-${timeStr}-compact-${trigger}`;

  let logFile = `${logDir}/${baseName}.md`;
  let counter = 2;
  try {
    while ((await Deno.stat(logFile)).isFile) {
      logFile = `${logDir}/${baseName}-${counter}.md`;
      counter++;
    }
  } catch {
    // File doesn't exist, good
  }

  const logContent = [
    "# Pre-Compact Session Summary",
    "",
    "## Session Info",
    `- Timestamp: ${now.toISOString()}`,
    `- Trigger: ${trigger}`,
    `- Session ID: ${sessionId}`,
    `- Branch: ${branch || "unknown"}`,
    `- HEAD: ${headSha.slice(0, 8) || "unknown"}`,
    `- Dirty files: ${dirtyFiles}`,
    "",
    "## Recent User Messages",
    "```",
    ...recentMsgs.map((m, i) => `${i + 1}. ${m}`),
    "```",
    "",
    `- Total transcript entries: ${totalEntries}`,
    "",
    "---",
    "*Auto-generated by PreCompact hook (TS)*",
  ].join("\n");

  await Deno.writeTextFile(logFile, logContent);
  await Deno.stderr.write(
    new TextEncoder().encode(`PreCompact: assets.json + log saved for session ${sessionId}\n`),
  );
}

main().catch((e) => {
  Deno.stderr.writeSync(
    new TextEncoder().encode(`PreCompact hook error: ${e}\n`),
  );
  Deno.exit(0); // Don't block compaction on error
});
