#!/bin/bash
# Pre-Compact Hook - Save session summary before context compaction
# Reads transcript to create comprehensive session handoff

set -e

# Read input from stdin
INPUT=$(cat)
TRIGGER=$(echo "$INPUT" | jq -r '.trigger // "unknown"')
TRANSCRIPT_PATH=$(echo "$INPUT" | jq -r '.transcript_path // ""')
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // "unknown"')

# Only proceed if in a project directory
if [ -z "$CLAUDE_PROJECT_DIR" ]; then
    exit 0
fi

# Generate filename
DATE=$(date '+%Y-%m-%d')
HOUR=$(date '+%H')
MINUTE=$(date '+%M')
BASE_NAME="${DATE}-${HOUR}${MINUTE}-compact-${TRIGGER}"

# Create sessions directory if needed
mkdir -p "$CLAUDE_PROJECT_DIR/ai/log/sessions"

# Find unique filename
FILENAME="$CLAUDE_PROJECT_DIR/ai/log/sessions/${BASE_NAME}.md"
COUNTER=2
while [ -f "$FILENAME" ]; do
    FILENAME="$CLAUDE_PROJECT_DIR/ai/log/sessions/${BASE_NAME}-${COUNTER}.md"
    ((COUNTER++))
done

# Collect session info
CURRENT_TIME=$(date '+%Y-%m-%d %H:%M:%S')

# Check if git repo
IS_GIT_REPO=false
if git -C "$CLAUDE_PROJECT_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    IS_GIT_REPO=true
fi

# Build session document
{
    echo "# Pre-Compact Session Summary"
    echo ""
    echo "## Session Info"
    echo "- Timestamp: $CURRENT_TIME (JST)"
    echo "- Trigger: $TRIGGER"
    echo "- Session ID: $SESSION_ID"

    if [ "$IS_GIT_REPO" = true ]; then
        cd "$CLAUDE_PROJECT_DIR"
        echo "- Branch: $(git branch --show-current 2>/dev/null || echo 'detached')"
        echo ""

        # Today's commits
        TODAY_COMMITS=$(git log --since="midnight" --oneline 2>/dev/null | wc -l | tr -d ' ')
        if [ "$TODAY_COMMITS" -gt 0 ]; then
            echo "## Today's Commits ($TODAY_COMMITS)"
            echo "\`\`\`"
            git log --since="midnight" --oneline 2>/dev/null | head -10
            echo "\`\`\`"
            echo ""
        fi

        # Uncommitted changes
        UNCOMMITTED=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
        if [ "$UNCOMMITTED" -gt 0 ]; then
            echo "## Uncommitted Changes ($UNCOMMITTED files)"
            echo "\`\`\`"
            git status --short 2>/dev/null | head -20
            echo "\`\`\`"
            echo ""
        fi
    fi

    # Extract conversation summary from transcript
    if [ -n "$TRANSCRIPT_PATH" ] && [ -f "$TRANSCRIPT_PATH" ]; then
        echo "## Conversation Analysis"
        echo ""

        # Count messages
        TOTAL_LINES=$(wc -l < "$TRANSCRIPT_PATH" | tr -d ' ')
        echo "- Total transcript entries: $TOTAL_LINES"
        echo ""

        # Extract user messages (last 5)
        echo "### Recent User Requests"
        echo "\`\`\`"
        # Try to extract user messages - format may vary
        jq -r 'select(.type == "human" or .role == "user") | .message // .content // .text // empty' "$TRANSCRIPT_PATH" 2>/dev/null | tail -5 || echo "(Could not parse user messages)"
        echo "\`\`\`"
        echo ""

        # Extract tool usage summary
        echo "### Tools Used"
        echo "\`\`\`"
        jq -r 'select(.type == "tool_use" or .tool_name != null) | .tool_name // .name // empty' "$TRANSCRIPT_PATH" 2>/dev/null | sort | uniq -c | sort -rn | head -10 || echo "(Could not parse tool usage)"
        echo "\`\`\`"
        echo ""

        # Extract file paths mentioned
        echo "### Files Touched"
        echo "\`\`\`"
        jq -r '.. | .file_path? // .path? // empty' "$TRANSCRIPT_PATH" 2>/dev/null | sort -u | head -20 || echo "(Could not parse file paths)"
        echo "\`\`\`"
        echo ""
    fi

    echo "---"
    echo "*Auto-generated by PreCompact hook at context window compaction*"

} > "$FILENAME"

# Output for debug log
echo "Session summary saved: $FILENAME" >&2

exit 0
