[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
on_i = 1
[[plugins]]
repo = 'zchee/deoplete-jedi'
hook_add = '''
    let g:deoplete#sources#jedi#python_path = '/usr/local/bin/python3.7'
'''
[[plugins]]
repo = 'cespare/vim-toml'
[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
  let g:go_fmt_command = "goimports"
  let g:go_def_mapping_enabled = 0
  let g:go_doc_keywordprg_enabled = 0
'''
[[plugins]]
repo = 'zchee/deoplete-go'
[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
[[plugins]]
repo = 'w0rp/ale'
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'natebosch/vim-lsc'
