[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
on_i = 1
[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'cespare/vim-toml'
[[plugins]]
repo = 'fatih/vim-go'
[[plugins]]
repo = 'zchee/deoplete-go'
[[plugins]]
repo = 'tell-k/vim-autopep8'
[[plugins]]
repo = 'Yggdroot/indentLine'
